package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN = 4
const PLAYER_ATTACK_MAX = 8
const PLAYER_SPECIAL_ATTACK_MIN = 6
const PLAYER_SPECIAL_ATTACK_MAX = 12
const PLAYER_HEAL_MIN = 6
const PLAYER_HEAL_MAX = 10

const MONSTER_ATTACK_MIN = 7
const MONSTER_ATTACK_MAX = 14